### PR TITLE
Fix terminal setting and use separator between prompts

### PR DESCRIPTION
**Pull request by CeleritasCelery**
This PR does two things:

First, it hardcodes the terminal setting to dumb. This is the default, but if the user happens to be using a different setting (as I am) then it will break aider since it is built on prompt-toolkit.

Second, Aider will output a series of Unicode dashes between the prompts. However, it doesn't query for the correct size and instead just hardcodes the number of dashes to insert. Emacs already has a nice way to handle these separators via `page-break-lines`. This has the advantage that it will always span the entire window, even when resizing.

### CODE REVIEW

**Comment by tninja** [comment]
Hi @CeleritasCelery, Thanks for the PR! I tried your change in my laptop, comments:

1. For the first commit, it might be a good idea. actually i have little knowledge about comint-terminfo-terminal.
2. For the second one, i only saw slightly color change on the page break line,
Screenshot 2024-10-21 at 8 00 18 PM
 
and the previous one before change seems OK to me? (I am using a Macbook Pro)
Screenshot 2024-10-21 at 8 00 56 PM

**Comment by CeleritasCelery** [comment]
The old separator is hardcoded to 80 characters (because the terminal is dumb). If the window is narrower than that it will wrap and if it is wider it will not span the whole line. It is not a big thing, but I feel like it makes the interface nicer.

**Comment by tninja** [comment]
Got it. Thanks for the replying. Is there a way to achieve that without adding a package dependency?

**Comment by CeleritasCelery** [comment]
I implemented a dependency-free solution based on [this](https://github.com/leodag/form-feed-st) code. I think it looks better overall.

**Comment by tninja** [comment]
Tested and it works. Thanks for the contribution.

**Pull request merged**
